/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteRouteImport } from './routes/_authed/route'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthedSentenceTranslatorIndexRouteImport } from './routes/_authed/sentence-translator/index'
import { Route as AuthedQuizGeneratorIndexRouteImport } from './routes/_authed/quiz-generator/index'

const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedSentenceTranslatorIndexRoute =
  AuthedSentenceTranslatorIndexRouteImport.update({
    id: '/sentence-translator/',
    path: '/sentence-translator/',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedQuizGeneratorIndexRoute =
  AuthedQuizGeneratorIndexRouteImport.update({
    id: '/quiz-generator/',
    path: '/quiz-generator/',
    getParentRoute: () => AuthedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/quiz-generator/': typeof AuthedQuizGeneratorIndexRoute
  '/sentence-translator/': typeof AuthedSentenceTranslatorIndexRoute
}
export interface FileRoutesByTo {
  '/auth/login': typeof AuthLoginRoute
  '/': typeof AuthedIndexRoute
  '/quiz-generator': typeof AuthedQuizGeneratorIndexRoute
  '/sentence-translator': typeof AuthedSentenceTranslatorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/quiz-generator/': typeof AuthedQuizGeneratorIndexRoute
  '/_authed/sentence-translator/': typeof AuthedSentenceTranslatorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth/login' | '/quiz-generator/' | '/sentence-translator/'
  fileRoutesByTo: FileRoutesByTo
  to: '/auth/login' | '/' | '/quiz-generator' | '/sentence-translator'
  id:
    | '__root__'
    | '/_authed'
    | '/auth/login'
    | '/_authed/'
    | '/_authed/quiz-generator/'
    | '/_authed/sentence-translator/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/sentence-translator/': {
      id: '/_authed/sentence-translator/'
      path: '/sentence-translator'
      fullPath: '/sentence-translator/'
      preLoaderRoute: typeof AuthedSentenceTranslatorIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/quiz-generator/': {
      id: '/_authed/quiz-generator/'
      path: '/quiz-generator'
      fullPath: '/quiz-generator/'
      preLoaderRoute: typeof AuthedQuizGeneratorIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
  }
}

interface AuthedRouteRouteChildren {
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedQuizGeneratorIndexRoute: typeof AuthedQuizGeneratorIndexRoute
  AuthedSentenceTranslatorIndexRoute: typeof AuthedSentenceTranslatorIndexRoute
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedQuizGeneratorIndexRoute: AuthedQuizGeneratorIndexRoute,
  AuthedSentenceTranslatorIndexRoute: AuthedSentenceTranslatorIndexRoute,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
