/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SentenceTranslatorIndexRouteImport } from './routes/sentence-translator/index'
import { Route as QuizGeneratorIndexRouteImport } from './routes/quiz-generator/index'
import { Route as AuthLoginRouteImport } from './routes/auth/login'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SentenceTranslatorIndexRoute = SentenceTranslatorIndexRouteImport.update({
  id: '/sentence-translator/',
  path: '/sentence-translator/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizGeneratorIndexRoute = QuizGeneratorIndexRouteImport.update({
  id: '/quiz-generator/',
  path: '/quiz-generator/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/quiz-generator/': typeof QuizGeneratorIndexRoute
  '/sentence-translator/': typeof SentenceTranslatorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/quiz-generator': typeof QuizGeneratorIndexRoute
  '/sentence-translator': typeof SentenceTranslatorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/quiz-generator/': typeof QuizGeneratorIndexRoute
  '/sentence-translator/': typeof SentenceTranslatorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth/login' | '/quiz-generator/' | '/sentence-translator/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth/login' | '/quiz-generator' | '/sentence-translator'
  id:
    | '__root__'
    | '/'
    | '/auth/login'
    | '/quiz-generator/'
    | '/sentence-translator/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthLoginRoute: typeof AuthLoginRoute
  QuizGeneratorIndexRoute: typeof QuizGeneratorIndexRoute
  SentenceTranslatorIndexRoute: typeof SentenceTranslatorIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sentence-translator/': {
      id: '/sentence-translator/'
      path: '/sentence-translator'
      fullPath: '/sentence-translator/'
      preLoaderRoute: typeof SentenceTranslatorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz-generator/': {
      id: '/quiz-generator/'
      path: '/quiz-generator'
      fullPath: '/quiz-generator/'
      preLoaderRoute: typeof QuizGeneratorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthLoginRoute: AuthLoginRoute,
  QuizGeneratorIndexRoute: QuizGeneratorIndexRoute,
  SentenceTranslatorIndexRoute: SentenceTranslatorIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
